apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: foobar-com-tls-profile
  namespace: default
spec:
  hosts:
  - foobar.com
  tls:
    clientSSL: /Common/foobar-clientssl
    reference: bigip
    serverSSL: ""
    termination: edge
