apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: ocbc-nomonitor
  labels:
    f5cr: "true"
spec:
  domainName: nomonitor.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: h1.nomonitor.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: H1-ServerL
