apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: ocbc-http-monitor
  labels:
    f5cr: "true"
spec:
  domainName: example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: h1.http-monitor.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: H1-ServerL
    monitor:
      type: http
      send: /
      recv: ""
      interval: 10
      timeout: 10
