apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: ocbc-foo-h2
  labels:
    f5cr: "true"
spec:
  domainName: foo.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: h2.foo.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: H2-ServerL
    monitor:
      type: https
      send: "GET /health\r\n"
      recv: ""
      interval: 10
      timeout: 10
