apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: foo-com-tls-profile
  namespace: default
spec:
  hosts:
  - foo.com
  tls:
    clientSSL: /Common/foo-clientssl
    reference: bigip
    serverSSL: ""
    termination: edge
