apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: bar-com-tls-profile
  namespace: default
spec:
  hosts:
  - bar.com
  tls:
    clientSSL: /Common/bar-clientssl
    reference: bigip
    serverSSL: ""
    termination: edge
